# Generated by Django 3.2.6 on 2021-12-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofile',
            name='url',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/<function user_path at 0x0000023FEF93FF70>'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='url',
            field=models.FileField(upload_to='photo/%Y/%m/%d/<function user_path at 0x0000023FEF93FF70>'),
        ),
    ]
