# Generated by Django 3.2.6 on 2021-12-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211216_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofile',
            name='url',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/<function user_path at 0x00000219C3AD0F70>'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='url',
            field=models.FileField(upload_to='photo/%Y/%m/%d/<function user_path at 0x00000219C3AD0F70>'),
        ),
    ]
