# Generated by Django 3.2.6 on 2021-12-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usermodel_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbie',
            name='user',
        ),
        migrations.AlterField(
            model_name='hobbie',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, to='main.Hobbie'),
        ),
    ]
