# Generated by Django 3.2.6 on 2021-12-17 20:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211217_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbie',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='photofile',
            name='url',
            field=models.ImageField(blank=True, upload_to=main.models.user_directory_path),
        ),
    ]
